var path = require('path');
var webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

var host = process.env.HOST || 'localhost';
var port = process.env.PORT || '8080';

module.exports = {
  entry: [
    'webpack-dev-server/client?http://'+host+':'+port,
    'webpack/hot/only-dev-server',
    path.resolve(__dirname, '..', 'src/index')
  ],
  output: {
      filename: 'js/index.js',
      path: path.resolve(__dirname, '..', '/build'),
      publicPath: '/',
      sourceMapFilename: 'debugging/[file].map',
      library: 'react-solitaire',
      libraryTarget: 'umd'
  },
  resolve: {
    extensions: ['', '.jsx', '.js', '.json'],
    modulesDirectories: ['node_modules', 'src'],
  },
  module: {
    loaders: [{
        test: /\.scss$/,
        loaders: ["style", "css", "sass"] 
      }, {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      }, {
        test: /\.(png|jpg|svg)$/,
        loader: 'url-loader?limit=1048576'
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Make hot loading work,
    new HtmlWebpackPlugin({
      template: 'index.html', // Move the index.html file

      // inject all files that are generated by webpack,
      // e.g. bundle.js, main.css with the correct HTML tags
      inject: true
    })
  ],
  devtool: 'eval'
};
